# test of policy scan issue importer

name: Policy scan and Issue importer

on: [push, pull_request, workflow_dispatch]

jobs:
  get-policy-flaws:
    #needs: env-testing
    runs-on: ubuntu-latest
    #environment: veracode
    container: 
      image: veracode/api-signing:latest
      env:
        VERACODE_API_KEY_ID: ${{ secrets.VERACODE_API_ID }}
        VERACODE_API_KEY_SECRET: ${{ secrets.VERACODE_API_KEY }}
      #options: --user root
    steps:
      # Note: this will likely fail if there are more than 500 flaws, due to Veracode results limiting
      #   (would need a more elaborate method)
      #
      # Note 2: Assumes Environment Secrets of VERACODE_API_KEY_ID and VERACODE_API_KEY_SECRET
      #   (not Repo Secrets)
      - name: get policy flaws
        run: |
          cd /tmp
          which jq
          export VERACODE_API_KEY_ID=ae0210a7e2f7615c0181d74c5eebd2ec
          export VERACODE_API_KEY_SECRET=ebba3e755dd93ca89cf5f455b6449cd297af6cd79ebca3b61ad3056e9587f04ddfaaf47e823b1455f2cb10bb499bb0f117683bbd4439db89aedfc9fc1313f304
          http --auth-type veracode_hmac "https://api.veracode.com/appsec/v1/applications?name=NodeGoat"
          echo TAKE 2
          http --auth-type veracode_hmac https://api.veracode.com/appsec/v1/applications?name=NodeGoat
          guid=$(http --auth-type veracode_hmac "https://api.veracode.com/appsec/v1/applications?name=NodeGoat" | jq -r '._embedded.applications[0].guid') 
          echo GUID: ${guid}
          total_flaws=$(http --auth-type veracode_hmac "https://api.veracode.com/appsec/v2/applications/${guid}/findings?scan_type=STATIC&violates_policy=True" | jq -r '.page.total_elements')
          echo TOTAL_FLAWS: ${total_flaws}
          http --auth-type veracode_hmac "https://api.veracode.com/appsec/v2/applications/${guid}/findings?scan_type=STATIC&violates_policy=True&size=${total_flaws}" > policy_flaws.json
          ls -l

      - name: save results file
        uses: actions/upload-artifact@v2
        with:
          name: policy-flaws
          path: /tmp/policy_flaws.json

  import-policy-flaws:
    needs: get-policy-flaws
    runs-on: ubuntu-latest
    steps:
      - name: get flaw file
        uses: actions/download-artifact@v2
        with:
          name: policy-flaws
          path: /tmp

      - name: debug1
        run: |
          pwd
          ls -l
          ls -l /tmp

      - name: import flaws as issues
        uses: buzzcode/veracode-flaws-to-issues@main
        with:
          scan-results-json: '/tmp/policy_flaws.json'
          github-token: ${{ secrets.GITHUB_TOKEN }}


